version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=True
      - ALLOWED_ORIGINS=["http://localhost:3000", "http://localhost:5173"]
      # Google Ads API (uncomment and fill to enable)
      # - GOOGLE_ADS_DEVELOPER_TOKEN=...
      # - GOOGLE_ADS_CLIENT_ID=...
      # - GOOGLE_ADS_CLIENT_SECRET=...
      # - GOOGLE_ADS_REFRESH_TOKEN=...
      # - GOOGLE_ADS_CUSTOMER_ID=...
      # Microsoft Ads API (optional fallback)
      # - MSADS_DEVELOPER_TOKEN=...
      # - MSADS_CLIENT_ID=...
      # - MSADS_CLIENT_SECRET=...
      # - MSADS_REFRESH_TOKEN=...
      # - MSADS_CUSTOMER_ID=...
      # - MSADS_ACCOUNT_ID=...
      # SerpAPI (discovery fallback)
      # - SERPAPI_KEY=...
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

networks:
  default:
    name: sem_plan_network
